use MER6;
select RESERVA.DATA_RESERVA, RESERVA.IMPORT_TOTAL, VOL.NUM_VOL, PASSATGER.NOM, PASSATGER.COGNOM
FROM RESERVA, VOL, PASSATGER
WHERE PASSATGER.ID=RESERVA.PASSATGER_ID AND VOL.ID=RESERVA.VOL_ID AND PASSATGER.NOM="Pepe";