use MER6;
SELECT PASSATGER.DNI, PASSATGER.NOM, PASSATGER.COGNOM, VOL.NUM_VOL, VOL.ORIGEN, VOL.DESTI, RESERVA.IMPORT_TOTAL
FROM PASSATGER, VOL, RESERVA
WHERE PASSATGER.ID=RESERVA.PASSATGER_ID and
VOL.ID=RESERVA.VOL_ID;