use MER7;
SELECT count(LINIA_TICKET.ID) as "Nom de empleats que comenca per J"
FROM LINIA_TICKET, TICKET, EMPLEAT
WHERE TICKET.ID = LINIA_TICKET.TICKET_ID AND
EMPLEAT.ID=TICKET.EMPLEAT_ID AND
EMPLEAT.NOM LIKE "J%";