use MER7;
SELECT TICKET.NUM_FACTURA, TICKET.DATA_TICKET, EMPLEAT.NOM, EMPLEAT.COGNOM
FROM TICKET, EMPLEAT, LINIA_TICKET, PRODUCTE
WHERE PRODUCTE.ID=LINIA_TICKET.PRODUCTE_ID AND
TICKET.ID=LINIA_TICKET.TICKET_ID AND
EMPLEAT.ID=TICKET.EMPLEAT_ID AND
PRODUCTE.NOM="Taula";